apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: privaterepo
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/jakubpetrovic/argo-apps-test.git
        revision: HEAD
        files:
        - path: "apps/**/config.json"
  template:
    metadata:
      name: "{{ app.name }}"
    spec:
      project: app-project # project is restricted
      source:
        # developers may customize app details using JSON files from above repo URL
        repoURL: "{{app.source}}"
        targetRevision: env-dev
        path: "{{app.path}}"
        helm:
          releaseName: "{{ app.name }}"
          valueFiles:
            - "values-dev.yaml"
      destination:
        server: https://kubernetes.default.svc # cluster is restricted
        namespace: argocd # namespace is restricted