apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: services
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: pro
            url: https://kubernetes.default.svc
  template:
    metadata:
      name: "{{cluster}}-services"
    spec:
      project: default
      source:
        repoURL: https://github.com/jakubpetrovic/k8s-playground
        targetRevision: HEAD
        path: apps/app1/test-app
      destination:
        server: "{{url}}"
        namespace: default
