apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apprender
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - appName: app1
          - appName: app2
  template:
    metadata:
      name: "{{ appName }}"
    spec:
      project: app-project
      source:
        repoURL: https://github.com/jakubpetrovic/k8s-playground.git
        targetRevision: HEAD
        path: apps/{{ appName }}/test-app
        helm:
          releaseName: "{{ appName }}"
          valueFiles:
            - "values.yaml"
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
