apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apprender
spec:
  generators:
    - list:
        elements:
          - app: app1
          - app: app2
  template:
    metadata:
      name: "app1"
    spec:
      project: app-project
      source:
        repoURL: https://github.com/jakubpetrovic/k8s-playground.git
        targetRevision: HEAD
        path: apps/app1/test-app
        helm:
          releaseName: "app1"
          valueFiles:
            - "values.yaml"
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
