apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: ArgoCD project for testing
  sourceRepos:
    - '*'
    - {{ .Values.gitrepo }}
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.gitrepo }}
    targetRevision: main
    type: helm
    path: apps/test-app
    helm:
      releaseName: app1
      valueFiles: 
        - "values-dev.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: test-app
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1-prod
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.gitrepo }}
    targetRevision: env-prod
    type: helm
    path: apps/test-app
    helm:
      releaseName: app1-prod
      valueFiles: 
        - "values-prod.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: test-app
