apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: "apps-{{ .Values.environment }}"
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: ArgoCD project for testing
  sourceRepos:
    - '*'
    - {{ .Values.gitrepo }}
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "app1-{{ .Values.environment }}"
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: "apps-{{ .Values.environment }}"
  source:
    repoURL: {{ .Values.gitrepo }}
    targetRevision: "env-{{ .Values.environment }}"
    type: helm
    path: apps/test-app
    helm:
      releaseName: app1-prod
      valueFiles: 
        - "values-{{ .Values.environment }}.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: test-app
